---

docker_services:
  - atuin
  - audiobookshelf
  - authentik
  - caddy
  - grafana
  - hugo_blog
  - influxdb
  - jellyfin
  - navidrome
  - nextcloud
  - ovh_dyndns_updater
  - photoprism
  - prometheus
  - syncthing
  - uptime_kuma
  - vault
  - watchtower

backup_services:
  - atuin
  - audiobook
  - audiobookshelf
  - authentik
  - caddy
  - grafana
  - influxdb
  - jellyfin
  - music
  - navidrome
  - nextcloud
  - photoprism
  - pictures
  - prometheus
  - syncthing
  - uptime_kuma
  - vault

# vi:ft=yaml.ansible
