services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    stop_grace_period: 1m
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=true
    command:
      - --schedule
      # second  minute hour DoM Month DoWeek
      - "0 0 2 * * *"
    networks:
      - watchtower


networks:
  watchtower:
    external: true
