---

- name: Create required docker networks
  community.docker.docker_network:
    name: frontend

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - jellyfin_config
    - jellyfin_cache
  loop_control:
    loop_var: docker_volumes

- name: Deploy env file
  template:
    src: env.j2
    dest: '{{ homeserver_repo_dir }}/services/jellyfin/.env'

# vi:ft=yaml.ansible
