---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add appropriate repos
  tags:
    - repos
  import_tasks: 'repos.yml'

- name: Install required packages
  tags:
    - packages
  import_tasks: 'packages.yml'

- name: Setup fail2ban
  tags:
    - fail2ban
  import_tasks: 'fail2ban.yml'

- name: Set users
  import_tasks: 'users.yml'
  tags:
    - users

- name: Set firewall rules
  import_tasks: 'firewall.yml'
  tags:
    - firewall

- name: Deploy system-wide environment configuration
  copy:
    src: etc-environment
    dest: '/etc/environment'
    mode: '600'

- name: Deploy environment configuration for users
  template:
    src: homeserver_config.sh.j2
    dest: '/etc/profile.d/homeserver_config.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Install required packages
  import_tasks: 'docker.yml'

- name: Set unattended upgrades
  import_tasks: 'unattended-upgrades.yml'
  tags:
    - unattended-upgrades
