---

- name: Read restic secrets from vault
  tags:
    - always
  community.hashi_vault.vault_kv2_get:
    url: '{{ vault.url }}'
    path: restic
    engine_mount_point: homeserver_secrets
    auth_method: token
    token_path: '{{ homeserver_repo_dir }}/ansible/'
  register: restic_secrets

- name: Initialise restic repositories
  import_role:
    name: restic
    tasks_from: init
  tags:
    - backup

- name: Do the backup
  include_role:
    name: 'services/{{ backup_service }}'
    tasks_from: backup
    apply:
      tags:
        - '{{ backup_service }}'
  loop: '{{ backup_services }}'
  loop_control:
    loop_var: backup_service
  tags:
    - always

# vi:ft=yaml.ansible
