---

- name: 'reload fail2ban'
  service:
    name: 'fail2ban'
    state: 'reloaded'

- name: systemd_daemon_reload
  systemd:
    daemon_reload: yes

- name: 'reload sshd'
  service:
    name: 'sshd'
    state: 'reloaded'

- name: "reload firewalld"
  service:
    name: "firewalld"
    state: "reloaded"
