---

- name: Do Jellyfin backup
  tags:
    - backup
  include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_data:
      path:
      volumes:
        - jellyfin_config
        - jellyfin_cache
      tags:
        - jellyfin
      ignore_patterns:
      docker_data_dir: '{{ docker_data_dir }}'

- name: Prune Jellyfin snapshots
  include_role:
    name: restic
    tasks_from: forget
  vars:
    restic_forget_data:
      tags_intersect:
      tags_union:
        - jellyfin
      keep_daily: 10
      keep_weekly: 4
      keep_monthly: 4
      prune: true

# vi:ft=yaml.ansible
