services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    stop_grace_period: 1m
    depends_on:
      - loki
      - promtail
      - influxdb
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped
    networks:
      - monitoring
      - internal_monitoring
    environment: 
      - TZ="Europe/Stockholm"
      - GF_SERVER_DOMAIN=grafana.nelyah.eu
      - GF_SERVER_ROOT_URL=https://grafana.nelyah.eu

  loki:
    image: grafana/loki:latest
    container_name: loki
    stop_grace_period: 1m
    command: -config.file=/etc/loki/loki_config.yml
    volumes:
      - ./loki_config.yml:/etc/loki/loki_config.yml:ro
    restart: unless-stopped
    networks:
      - internal_monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    stop_grace_period: 1m
    command: -config.file=/etc/promtail/promtail_config.yml
    volumes:
      - ./promtail_config.yml:/etc/promtail/promtail_config.yml:ro
      - /var/log:/var/log:ro
    restart: unless-stopped
    networks:
      - internal_monitoring

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    stop_grace_period: 1m
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
    networks:
      - monitoring
    env_file:
      - influxdb.env
    environment: 
      - TZ="Europe/Stockholm"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    stop_grace_period: 1m
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    depends_on:
      - node_exporter
      - cadvisor
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
      - internal_monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
      # this is causing some issues with the collector failing because of
      # "invalid argument." since I am not using it especially, I disable it
      # to avoid having the process fail on repeat
      - '--no-collector.thermal_zone'
    networks:
      - internal_monitoring
    pid: host
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/:/host:ro,rslave'
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    stop_grace_period: 1m
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
    networks:
      - internal_monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /data/docker-data/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --housekeeping_interval=1m0s
      # The reference_memory metrics is disable because I was getting an error
      # when reading smap files... see https://github.com/google/cadvisor/issues/3139
      - --disable_metrics=disk,referenced_memory
    devices:
      - /dev/kmsg
    restart: unless-stopped

volumes:
  grafana_data:
    external: true
  influxdb_data:
    external: true
  prometheus_data:
    external: true

networks:
  monitoring:
    external: true
  internal_monitoring:
    internal: true
