services:
  navidrome:
    container_name: navidrome
    image: docker.io/deluan/navidrome:develop
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      user: 1000:1000
      ND_DEVACTIVITYPANEL: "true"
      ND_SCANINTERVAL: "744h"
      ND_PORT: 80
      ND_TRANSCODINGCACHESIZE: 100MB
      ND_SESSIONTIMEOUT: "744h"
    networks:
      - navidrome
    volumes:
      - ${MUSIC_LIBRARY}:/music:ro
      - navidrome_data:/data/

  navidrome_mum:
    container_name: navidrome_mum
    image: docker.io/deluan/navidrome:develop
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      user: 1000:1000
      ND_DEVACTIVITYPANEL: "true"
      ND_SCANINTERVAL: "744h"
      ND_PORT: 8080
      ND_TRANSCODINGCACHESIZE: 100MB
      ND_SESSIONTIMEOUT: "744h"
    networks:
      - navidrome
    volumes:
      - ${MUSIC_LIBRARY_MUM}:/music:ro
      - navidrome_mum_data:/data/

volumes:
  navidrome_data:
    external: true
  navidrome_mum_data:
    external: true

networks:
  navidrome:
    external: true
