services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    stop_grace_period: 1m
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
      # this is causing some issues with the collector failing because of
      # "invalid argument." since I am not using it especially, I disable it
      # to avoid having the process fail on repeat
      - '--no-collector.thermal_zone'
    networks:
      - grafana
    pid: host
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/:/host:ro,rslave'
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  cadvisor:
    # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    stop_grace_period: 1m
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
    networks:
      - grafana
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /data/docker-data/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --housekeeping_interval=1m0s
      # The reference_memory metrics is disable because I was getting an error
      # when reading smap files... see https://github.com/google/cadvisor/issues/3139
      - --disable_metrics=disk,referenced_memory
    devices:
      - /dev/kmsg
    restart: unless-stopped

  smartctl_exporter:
    build: exporters
    container_name: smartctl_exporter
    stop_grace_period: 1m
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    restart: unless-stopped
    command:
      - --reload
      - --port
      - '8000'
    environment:
      SMART_DEVICES: /dev/sda:/dev/sdb:/dev/sdc
    networks:
      - grafana
    volumes:
      - /dev:/dev:ro


volumes:
  prometheus_data:
    external: true
  prometheus_config:
    external: true

networks:
  grafana:
    external: true
