services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - frontend
    env_file:
      - .env
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - type: bind
        source: ${MOVIE_FOLDER}
        target: /movies
      - type: bind
        source: ${TVSHOWS_FOLDER}
        target: /tv_shows
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  jellyfin_config:
    external: true
  jellyfin_cache:
    external: true

networks:
  frontend:
    external: true
