---

docker_services:
  - atuin
  - audiobookshelf
  - authentik
  - caddy
  - emby
  - ghost
  - grafana
  - influxdb
  - jellyfin
  - navidrome
  - nextcloud
  - ovh_dyndns_updater
  - photoprism
  - prometheus
  - signal_api
  - syncthing
  - uptime_kuma
  - vault
  - watchtower
  - wordpress

backup_services:
  - atuin
  - audiobook
  - audiobookshelf
  - authentik
  - caddy
  - emby
  - ghost
  - grafana
  - influxdb
  - jellyfin
  - music
  - navidrome
  - nextcloud
  - photoprism
  - pictures
  - prometheus
  - syncthing
  - uptime_kuma
  - vault
  - wordpress

# vi:ft=yaml.ansible
