services:
  signal_api:
    image: bbernhard/signal-cli-rest-api
    container_name: signal_api
    restart: always
    networks:
      - internal
    volumes:
      - signal_api_data:/app/data

volumes:
  signal_api_data:
    external: true

networks:
  internal:
    external: true
